language: node_js

node_js: 
  - "12"

cache:
    apt: true
    directories:
        - node_modules

before_install:
  - echo install hexo

install:
  - npm install

before_script:
  - echo clean old file
  - hexo clean
  - echo create new file
  - hexo g
  - cd ./public
  - ls -l

script:
  - echo 開始部署...
  - git init
  - git config --global user.name "f820602h"
  - git config --global user.email "f820602h@gmail.com"
  - git add ./
  - MESSAGE=`date +\ %Y-%m-%d\ %H:%M:%S`
  - git commit -m "Site updated:$MESSAGE"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:gh-pages

after_script:
  - echo 部署完成！

branches:
  only:
    - master

env:
  global:
    - GH_REF: github.com/f820602h/Max-Blog.git