# Header
menu:
  Home: /
  Article: /archives
rss: /atom.xml

# Content
excerpt_link: 閱讀全文
fancybox: true

# Sidebar
sidebar: null
widgets:
- category
- tag
# - tagcloud
# - archive
- recent_posts

# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
# - category
# - tagcloud
# - archive

# widget behavior
archive_type: 'monthly'
show_count: false

# Miscellaneous
google_analytics:
gauges_analytics:
favicon: css/images/favicon.ico
twitter:
google_plus:
fb_admins:
fb_app_id:

# Disqus 
disqus_shortname: f820602h

# Emoji 
emoji:
  enable: true
  className: github-emoji